RS-180: Web console shows license information
reductstore/web-console pull request #64
Opened 2024-03-21 13:15 UTC by AnthonyCvn

Closes #

### Please check if the PR fulfills these requirements

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Feature

### What was changed?

A tab to show the license information.

Sample license:
<img width="1136" alt="license-info" src="https://github.com/reductstore/web-console/assets/26444489/29b304ce-484e-4e5d-b409-0e7a612eef09">

No license:
<img width="1133" alt="no-license" src="https://github.com/reductstore/web-console/assets/26444489/e7fde521-6f30-427a-98cb-6ba6cb31abcd">

Usage tab:
<img width="1132" alt="server-usage" src="https://github.com/reductstore/web-console/assets/26444489/d61ccc1e-3b30-4ea2-a571-bfd74516536b">

### Related issues

No

### Does this PR introduce a breaking change?

Yes, it works only with reduct-js > 1.9.1

### Other information:

A bug fix was needed on reduct-js to use it on the browser. Please update to reduct-js > 1.9.1 to test the web console.

2024-03-21 13:18 UTC, AnthonyCvn commented
@atimin I need a first review from you to check if the layout is good. I will write some tests once validated.

2024-03-22 09:30 UTC, atimin requested changes
I love the idea to use a tab for the license information. Looks great for me.

Few minor remarks:

1. Expire data looks strange on my side:
![image](https://github.com/reductstore/web-console/assets/67068/cd2885e0-e67e-46d4-ac2d-d6a7f5e2b4e6)

2. Maybe we could use bold font for names of field:

**Plan**: UNLIMITED

3. Don't forget that we need validation as well. See here the example: 

https://github.com/reductstore/reductstore/blob/main/reduct_cli/src/io/reduct.rs#L38

2024-03-22 15:31 UTC, AnthonyCvn commented
@atimin everything should be good and tested :) Please have a look. Just a small point, I assumed the expiration date from the license to return the number of milliseconds since midnight, January 1, 1970 (UTC), I think it's the case, but just to double check.

2024-03-22 15:32 UTC, AnthonyCvn commented
<img width="1140" alt="Screenshot 2024-03-22 at 16 32 05" src="https://github.com/reductstore/web-console/assets/26444489/1ed1e8f7-8597-4ae9-87ff-7f32e4b87fe3">

2024-03-22 15:55 UTC, atimin requested changes
Looks great but there are mistakes. See my comments. 

Is it possible to add an icon the License tab header  when it is BUSL or expired. So the users can see that there is a problem without clicking on the tab.

2024-03-22 15:55 UTC, atimin commented on src/Components/LicenseDetails/LicenseDetails.tsx
> +  const isOverQuota = usage > BigInt(license.diskQuota);
0 means unlimited.

2024-03-22 15:55 UTC, atimin commented on src/Components/LicenseDetails/LicenseDetails.tsx
> +  const isOverQuota = usage > BigInt(license.diskQuota);
I think we could even show it in Disk Quota field.

2024-03-22 15:55 UTC, atimin commented on src/Components/LicenseDetails/LicenseDetails.tsx
> +  const isOverQuota = usage > BigInt(license.diskQuota);
And it is in terabytes

2024-03-22 15:55 UTC, atimin commented on src/Components/LicenseDetails/LicenseDetails.tsx
> +      {alertExplanation && <div className="licenseAlert"><LicenseAlert alertExplanation={alertExplanation} /></div>}
![image](https://github.com/reductstore/web-console/assets/67068/cd94d530-4796-4fbf-a411-243130c5f487)

I'm not sure if the mentioning of BUSL is relevant here. Maybe we could say that they must contact us to extend it.

2024-03-26 20:33 UTC, atimin approved these changes
Perfect!

2024-03-27 09:54 UTC, merged